#!/bin/bash
#PBS -l select=1:ncpus=4:mem=64gb:ngpus=1
#PBS -l walltime=36:00:00
#PBS -N adlsys_cw
#PBS -e /rds/general/user/hn621/home/mase/docs/source/modules/documentation/tutorials/

# Setup environment
module load tools/dev
module load CUDA/11.8.0
module load miniforge/3

eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate mase

# Change to the working directory when submitting the job
cd $PBS_O_WORKDIR

# Run scripts
python3 ./tutorial_6_mixed_precision_search.py